import ExactNN

#print axioms ExactNN.relu_zero
#print axioms ExactNN.relu_nonneg
#print axioms ExactNN.le_relu
#print axioms ExactNN.relu_of_nonneg
#print axioms ExactNN.relu_of_nonpos
#print axioms ExactNN.relu_mul
#print axioms ExactNN.relu_sub_relu_neg
#print axioms ExactNN.relu_eq_iff
#print axioms ExactNN.relu_target_iff
#print axioms ExactNN.affine_scale
#print axioms ExactNN.affine_shift
#print axioms ExactNN.common_implies_mixed
#print axioms ExactNN.exactFit_mono
#print axioms ExactNN.exactFit_constant
#print axioms ExactNN.exactFit_zero_iff
#print axioms ExactNN.exactFit_no_conflict
#print axioms ExactNN.gram_kernel_iff
#print axioms ExactNN.linear_infeasible_of_certificate
#print axioms ExactNN.firstResolved_sound
#print axioms ExactNN.oneFit_iff_positive_or_negative
#print axioms ExactNN.relu_shift
#print axioms ExactNN.positiveFit_iff_lp_at_min
#print axioms ExactNN.oneFit_iff_twoLP
#print axioms ExactNN.vectorOneFit_coordinate
#print axioms ExactNN.vectorOneFit_collinear
#print axioms ExactNN.vectorOneFit_of_coordinate
#print axioms ExactNN.vectorOneFit_iff_collinear_coordinate
#print axioms ExactNN.vectorOneFit_constant
#print axioms ExactNN.collinear_direction_ratio
#print axioms ExactNN.univariate_hinge_identity
#print axioms ExactNN.univariate_term_decomposition
#print axioms ExactNN.mixedFit_iff_shallow_one
#print axioms ExactNN.exactFit_dim_one_iff_mixed
#print axioms ExactNN.hinge_reflection
#print axioms ExactNN.hinge_orientation
#print axioms ExactNN.secant_left_eq_right_sub_one
#print axioms ExactNN.curvature_orientation_invariant
#print axioms ExactNN.common_left_iff_reflected_right
#print axioms ExactNN.pair_reconstruction
#print axioms ExactNN.merge_hinges_outside_gap
#print axioms ExactNN.samples_eq_of_differences
#print axioms ExactNN.helper_count_bound
#print axioms ExactNN.unique_helpers_at_bound
#print axioms ExactNN.residue_eq_iff_of_abs_sub_lt
#print axioms ExactNN.cardinality_window
#print axioms ExactNN.cardinality_residue_iff
#print axioms ExactNN.Shallow.eval_pad
#print axioms ExactNN.exactFit_iff_slots
#print axioms ExactNN.exactFit_one_iff
#print axioms ExactNN.signCoeff_cases
#print axioms ExactNN.normalize_term
#print axioms ExactNN.Shallow.eval_normalize
#print axioms ExactNN.exactFit_iff_sharedComplementarity
#print axioms ExactNN.binary_product_iff
#print axioms ExactNN.bigM_relu_iff
#print axioms ExactNN.Expr.eval_substitute
#print axioms ExactNN.coupled_feasibility
#print axioms ExactNN.Shallow.eval_reindex
#print axioms ExactNN.exactFit_resample
